# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catlogrow',
            name='rowId',
            field=models.IntegerField(default=0),
        ),
    ]
