# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0002_catlogrow_rowid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatlogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='catlogrow',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.CatlogTable'),
        ),
    ]
